apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask
  labels:
    app: kubernetes_flask_sba_app
    tier: frontend
spec:
  
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: kubernetes-sba
        image: jasonautomation/kubernetes-sba-docker-image